name: End-to-end tests 🧪

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Delete node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Clean install dependencies
        run: npm install --force

      - name: Check Cypress version
        run: npx cypress --version

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
